# -*- coding: utf-8 -*-
"""system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1er_pUK8Jj5mk3mgqf9KCiF02JNmZpaJa
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the function to predict oil production
def predict_oil_production(porosity, rpm, drill_size):
    # Load the training data
    data = pd.read_csv('oil_production_data.csv')

    # Split the data into features and target
    X = data[['porosity', 'rpm', 'drill_size']]
    y = data['oil_production']

    # Train the linear regression model
    model = LinearRegression()
    model.fit(X, y)

    # Make the prediction
    prediction = model.predict([[porosity, rpm, drill_size]])
    return prediction[0]

# Function to find the optimal RPM and drill size
def find_optimal_parameters(porosity):
    # Define the search range for RPM and drill size
    rpm_range = np.arange(100, 5001, 100)
    drill_size_range = np.arange(4.0, 12.1, 0.5)

    # Initialize variables to track the optimal parameters
    max_oil_production = 0
    optimal_rpm = 0
    optimal_drill_size = 0

    # Iterate through the search range and find the optimal parameters
    for rpm in rpm_range:
        for drill_size in drill_size_range:
            oil_production = predict_oil_production(porosity, rpm, drill_size)
            if oil_production > max_oil_production:
                max_oil_production = oil_production
                optimal_rpm = rpm
                optimal_drill_size = drill_size

    return optimal_rpm, optimal_drill_size, max_oil_production

# Create the Streamlit app
st.title("Oil Production Prediction")

# Get the user input for porosity
porosity = st.number_input("Enter the porosity (%)", min_value=0.0, max_value=100.0, value=20.0)

# Find the optimal RPM and drill size
optimal_rpm, optimal_drill_size, max_oil_production = find_optimal_parameters(porosity)

# Display the results
st.write(f"The optimal RPM is {int(optimal_rpm)}")
st.write(f"The optimal drill size is {optimal_drill_size:.2f} inches")
st.write(f"The maximum predicted oil production is {max_oil_production:.2f} barrels per day.")